### ISSUE TITLE
Getting values from Solar Charger without display

### ISSUE THREAD

**Issue by heeplr** [crathje/VotronicSRDuoDig#1]
Thank you for documenting this and all your work.

Did you at any point dump the initial negotiation between display and charge controller?
I'm using a Votronic MPP 430 Duo Digital, and I can't seem to retrieve any data.

I connected to the RS485 adapter, according to the 6P6C pinout:

    1 - RS485 - B
    2 - V_battery (n/c)
    3 - V_cc 5V (n/c)
    4 - GND
    5 - RS485 - A
    6 - GND

It just sends a short HIGH pulse every second on Pin 5.

I hoped to get some useful data by emulating the initial display negotiation. If you still have a dump beginning at bootup, that might be possible if you could post it somewhere.

**Comment by crathje** [comment]
For the old SR series that I have written this library for there was no need to send anything.
As soon as there was power on the solar panel the device was spitting out data. During night it was not sending anything at all - even when you pressed on the display there was nothing transmitted. The old Display was measuring the voltage on its own, at least that was my guess.
Do you have a solar panel connected? 

But how did you end up with RS485? The old devices were spitting out serial data with a 5V level and not some differential signal. I only had the TX wire and GND connected ever since since I was never transmitting anything towards the votronic device.

**Comment by crathje** [comment]
So I got my hands on a brand new Votronic MPP 430 Duo Digital and hooked it up to a DSO and LA.

Connected to the DSO I get the expected 5V logic level data (y-scale is set to 1V):
![20221023_MPP430-DSO-Hookup_s](https://user-images.githubusercontent.com/619036/197386936-37909247-50ae-4335-a63d-c90cdea1aa65.jpg)

Connected to the Logic Analyzer
![20221023_MPP430-LogicAnalyzer-Hookup_s](https://user-images.githubusercontent.com/619036/197386938-7e497833-424d-4580-a514-4d21f5271505.jpg)
I get the bytes pretty good at 1000baud:
![2022-10-23 MPP430 LogicAnalyzer](https://user-images.githubusercontent.com/619036/197386939-2190c2e4-1986-4b9e-a0be-ab8317625a01.png)
Notice the 
* 0xAA being the frame start
* 0x1A the ID or something, read this a while ago somewhere. I do have a charge booster from Votronic flying around, maybe this byte is different there...
* 0x37 0x04 which would be 0x0437 hex -> 1079 dec meaning something like 10.79V primary battery voltage I guess, would fit the empty LiPo pack I attached for testing
* 0xA2 0x08 which would be 0x08A2 hex -> 2210 dec meaning something like 22.10V solar voltage, would fit the two LiPo packs I attached to emulate a solar panel for a bit
* 0xAF 0x00 which would be 0x00AF hex -> 175 dec meaning something like 1.75A charging (cannot verify that at the moment due to lack of functional power meter)
* 0x00 0x00 0x00 0x14 0x22 0x00-> don't know :)
* 0x09 would be some status flags like AES is on, standby and so on
* 0x13 would be the checksum (result of 0x00^0x1A^0x37^0x04^0xA2^0x08^0xAF^0x00^0x00^0x00^0x00^0x14^0x22^0x00^0x09)

The charger was not spitting out any data before the fake solar panel was attached. I had a small 12V panel attached on my desk but that was only providing like 8V which did not cause any output. Just make sure you have some power input on the solar part and you should be seeing some data there.

**Comment by heeplr** [comment]
Thanks a ton for your effort! 

Indeed, it's not RS485 (I got confused by [this project](https://codeberg.org/scy/votonic) which uses a different Votronic device).

I had not connected a solar panel voltage and thus just got a short 5V pulse. With a voltage connected, the device is spitting out data.

A bit strange that the battery voltage isn't reported at night, where it's most interesting to detect deep discharge.

**Comment by heeplr** [comment]
i had a look at the protocol and I think I found some more info. This is the struct i'm using so far:

```
{
  uint8  preamble,           // always 0xAA
  uint8  model_id,           // always 0x1A for MPP 430 Duo Digital
  int16  battery_voltage,    // V*100
  int16  solar_voltage,      // V*100
  int16  charge_current,     // A*100
  uint8  flags1,             // unknown (always 0x00 in my tests)
  uint8  flags2,             // unknown (always 0x00 in my tests)
  uint8  flags3,             // unknown (always 0x00 in my tests)
  uint8  temperature,        // degree celsius
  uint8  charge_mode,        // dip switches
  uint8  flags4,             
  uint8  flags5,             
  uint8  checksum
}
```

charge_mode looks like:
```
            0x35: "lead_gel",
            0x22: "lead_agm1",
            0x2f: "lead_agm2",
            0x50: "lifepo4_13.9V",
            0x52: "lifepo4_14.2V",
            0x54: "lifepo4_14.4V",
            0x56: "lifepo4_14.6V",
            0x58: "lifepo4_14.8V"
```

i *think* that `flags4 & 0x1` represents "battery full" and `flags5 & 0x10` represents ">80%" indicators.
flags5 had 0x9 bits always set in my tests.

I plan to do more observations and also release some python code.

**Comment by crathje** [comment]
Nice findings.

The original code I put on here was for the old chargers/displays that are not compatible with the new ones anymore (at least according to the documentation). They were not sending the battery voltage but rather measured that one internally.

If you take a look at https://youtu.be/tXYK4e92x7Q?t=485 you will find some more explanations. 
And https://youtu.be/tXYK4e92x7Q?t=1072 for the charging state flags.
At https://youtu.be/tXYK4e92x7Q?t=1176 you can see the status flags (line 47 and below).

Funny part is, Votronic does not mention the temperature that you found.

The complete json is available at
https://github.com/SirReal-surreal/SirReal-surreal/blob/main/2021_08_16_Votronic.json

**Comment by heeplr** [comment]
interesting! I'm really not sure yet about the temperature, tho. I'll check tomorrow. 

I also can't confirm the status bit descriptions mentioned in the video. 
Like in your datagram I only get battery_status=0x00 and controller_status=0x09 which doesn't align to the description [in the video](https://youtu.be/tXYK4e92x7Q?t=1147) (charge phases "I", "U1", "U2" and "U3" and controller status "standby", "throttled" and "AES")

I'll try to correlate any changes when I observe them.

I also put [my small python thing](https://github.com/heeplr/votronic) online. It prints received datagrams as json to stdout.

**Comment by heeplr** [comment]
Just to confirm: I'm pretty sure now about temperature. It seems to be some sensor inside the controller.
I logged ambient temperature and it correlates pretty well to temp + load (not surprising - it gets warm under load).
Spikes in ambient temperature can be seen clearly in the data.
